# Generated by Django 5.0.1 on 2024-01-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_alter_researchmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchmodel',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
