# Generated by Django 5.0.1 on 2024-01-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_alter_researchmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
